- Documentation/Configuration/Nginx.rst
The encoding utf8 is not the preferred name of the character encoding in use. The preferred name is utf-8.
> Corrected wring charset

- Classes/Cache/Rule/StaticCacheable.php
- ext_localconf.php
$frontendController->isStaticCacheable() checks public property "no_cache",  methods isINTincScript() and isUserOrGroupSet(). The last two methods are already checked in Rule\NoIntScripts and Rule\NoUserOrGroupSet. So I added a local isStaticCacheable method to only check for no_cache property.
> Fix #34 - use local isStaticCacheble check in StaticCacheble rule

- Resources/Private/Templates/Htaccess.html
All variable output in the generated .htaccess is no longer being escaped to prevent breaking some HTTP headers.
resolve #41
> Disable variable escaping in generated .htaccess

- Classes/Cache/Rule/PageCacheable.php
- Classes/Cache/Rule/StaticCacheable.php
Correct spelling seems to be "cacheable", see: https://en.wiktionary.org/wiki/cacheable
Also, class names (PageCacheable and StaticCacheable) already have the correct spelling.
Related Issue
-------------
None, I consider it trivial change, but I can create one, if necessary.
> Fix spelling of "cacheable".

- Documentation/Configuration/Htaccess.rst
Static caches are delivered in these both cases: domain.tld/path and domain.tld/path/.
Changing the .htaccess as proposed disables the delivery through domain.tld/path, which can be handled by RealUrl if "appendMissingSlash" is configuired like "ifNotFile,redirect[301]". Otherwise i think a 404 is correct.
What do you think?
> [IMPROVEMENT] Duplicate Content is generated

- Classes/Cache/AbstractBackend.php
- Classes/Cache/Compression/GzipCompression.php
- Classes/Cache/StaticFileBackend.php
- Classes/Configuration.php
For our websites we wanted to get better compression. First we wanted to compress the generated gz file further with advancecomp. Additionally we wanted to compress the HTML with brotli. So we introduced a new signal for compression.
This raised a new problem if we were using scheduler tasks to garbage collect the generated files, because only the .html and .gz files were deleted, but not the generated .br files. Because of this, we introduced a new signal to extend the list of files, which would be deleted.
> New signals for compression and cached file removal

- Classes/Command/CacheCommandController.php
- Classes/Service/QueueService.php
Stop crawling new items after N seconds since scheduler task started.
This adds an optional argument to the command `runCacheBoostQueueCommand`. It complements the already existing argument `limitItems`.
This might come in handy if someone want to stop generating new caches using this function after a fixed time.
Example use-case: "Process up to 250 items in the queue, but do not start processing a new item after 5 minutes of total execution time".
Related Issue
-------------
None
More Details
------------
None
- Work in Progess? No
- Open Issues? No
> Add scheduler argument: stopProcessingAfter

- composer.json
The seocli package is slightly better for crawling websites. It should be suggest instead of the crawler extension.
(e.g. in combination with a CacheCommandController and scheduler, see also #53)
> Replace suggest of crawler with seocli

- .gitattributes
there is no reason to exclude docs in gitattributes. it is very helpful to have the docs offline as well
> [TASK] Allow README.md in composer installations

- Documentation/Configuration/Htaccess.rst
This adds the required .htaccess setup to work with the brotli generator.
It works with or without mod_brotli enabled in Apache.
Also fixed the code blocks to use apache instead of bash syntax and fixed
the FileMatch rules to be anchored to the end of the filename.
> Update .htaccess configuration for brotli support

- Classes/StaticFileCache.php
If the page was not found the cache-key $table:$uid can not be used and error 500 is generated by TYPO3 caching framework. This fix prevents page from beeing cached, if the ID was not found (404).
More Details
------------
TYPO3 Version	9.5.7
Webserver	nginx/1.10.3
PHP Version	7.3.5
Database (Default)	MySQL 5.7.24
> [BUGFIX] do not try to cache a page which uid could not get discovered

- ext_tables.sql
Clearing the cache will create a lot of boost queue entries
and creating a boost queue entry requires checking if it is already
present.
The fields required for that query were previously not indexed.
This change speeds up cache clears with boost mode dramatically.
> avoid tinytext and use an index on the cache url

- ext_tables.sql
To avoid a warning during database-migration, the key-length is explicitly set
Related Issue
-------------
https://typo3.slack.com/archives/C9LRD4LSJ/p1573750733017800
> Set key-length for cache_url on boost-queue table

- Classes/Cache/Rule/NoFakeFrontend.php
Yoast SEO provides a feature called "Snippet Preview" which leads to cache poisoning if the requests aren't ignored.
Related Issue
-------------
https://github.com/lochmueller/staticfilecache/issues/222
> Ignore Yoast SEO requests

- Configuration/RequestMiddlewares.php
SiteCacheable rule needs already loaded Site configuration
...
Related Issue
-------------
None
...
More Details
------------
- Work in Progress? No
- Open Issues? No
> [FIX] move PrepareMiddleware after SiteMiddleware

- Documentation/Configuration/Htaccess.rst
We do not have any .html part in the generated filename by the latest version
> Remove html part in the filename

- Resources/Private/Templates/Backend/Boost.html
There was a strange wording in the backend module. 
> There are 7154 items that **ways** for processing and 46 old items.
I changed it to
> There are 7154 items that **wait** for processing and 46 old items.
Of course, I did not change the formatting. The bold formatting here is only to mark the change.
Related Issue
-------------
none
More Details
------------
none
> [BUGFIX] Fix typo in backend module

- Classes/Service/ClientService.php
-------------
An empty `handler` array in TYPO3_CONF_VARS.HTTP was introduced in
https://review.typo3.org/c/Packages/TYPO3.CMS/+/61407
When an empty `handle` array is passed to the guzzle client,
an exception is thrown as guzzle expects `handler`
to be callable or unset.
```
[ERROR] request="…"  component="SFC.Staticfilecache.Service.ClientService": Problems in single request running: handler must be a callable / …/typo3_src-10.4.0/vendor/guzzlehttp/guzzle/src/Client.php:67
```
TYPO3 core initializes an handler stack from the handler
array. For compatibility reasons the staticfilecache
should do so as well.
Related Issue
-------------
#251
> [BUGFIX] Support TYPO3 v10 HTTP handler stack

- Resources/Private/Templates/Htaccess.html
This adds a ForceType directive to the .htaccess template, to make sure that Apache applies the correct cache headers configured by ModExpires.
In addition this also makes sure that Apache sends the proper Content-Type header, if ModHeaders is not available or the Content-Type header is not whitelisted for inclusion in the .htaccess.
See #258 for detailed information on why this fix is needed.
Related Issue
-------------
* Fixes #258
* (Probably Fixes) #253
More Details
------------
This change also obsoletes a lot of the `FilesMatch` directives in the main `.htaccess` file in the TYPO3 document root, but they do not conflict and removal should be discussed in a separate issue / PR.
> Force proper cache file MIME Type via .htaccess

- Classes/Service/HttpPushService.php
- ext_conf_template.txt
Add a possibility to select an area (head, body or complete html) to limit the http2 pushes to the resources found there.
If not set, the whole '<html>' tag is taken (as before).
I need this for a project of mine, maybe this could be useful also for others...
Related Issue
-------------
no open issue
> Possibility for http2 push area (head or body) restrictions

- Classes/Generator/HtaccessGenerator.php
works in apache 2.4.38. Can't verify on other versions.
...
Related Issue
-------------
...
More Details
------------
- Work in Progress?
- Open Issues?
> [FIX] do not remove double-quotes - just escape them

- Documentation/KnownProblems/Index.rst
- ext_conf_template.txt
In the supported versions of TYPO3 the cache tables are prefixed
with cache_ and not with cf_ anymore.
> Rename cache prefix from cf_ to cache_

- Classes/Middleware/GenerateMiddleware.php
This happens while Reflection API is used to observe this class, e.g. with `<f:debug/>`
> Prevent Exception for unaccessible property (Fixes #313)

- .gitignore
- Classes/Middleware/FallbackMiddleware.php
The FallbackMiddleware.php does not check whether brotli is supported.
> Allow brotli compression  in FallbackMiddleware.php

- Classes/Cache/Rule/NoFakeFrontend.php
Due to the deprecation https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.5/Deprecation-95293-StringUtilitystartsWithAndStringUtilityendsWith.html in Typo3 v11.5, it would be good to replace "StringUtility::endsWith" with the *native* "str_ends_with" function. 
Even if this is a PHP 8.0 function, since Typo3 v10.4.21 and v11.5.2 there is the polyfill "symfony/polyfill-php80" installed automatically. 
Means we can use it without filling up the deprecation log.
Maybe its would be good to raise the dependencies (^10.4.21 || ^11.5.2) in composer.json as well...
> Replace "StringUtility::endsWith" with "str_ends_with"

- Classes/Cache/RemoteFileBackend.php
As of https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.4/Deprecation-94684-GeneralUtilityShortMD5.html the Utility "GeneralUtility::shortMD5" has been deprecated and will be replaced with the native counterpart.
> Replace deprecated "GeneralUtility::shortMD5" function

- Documentation/Configuration/Nginx.rst
Example for NGINX like the one already provided for Apache via .htaccess within Htaccess.rst
Related Issue
-------------
None
More Details
------------
If EXT:solr and EXT:staticfilecache are in use, indexing request cause errors if cache is used as described in #200
> Update nginx example configuration for indexing via EXT:solr

- Classes/Command/BoostQueueCommand.php
- Classes/Command/FlushCacheCommand.php
- Classes/EventListener/AfterPackageDeactivationListener.php
- Classes/Exception.php
- Classes/Hook/DatamapHook.php
- Classes/Service/DateTimeService.php
- Classes/Service/EnvironmentService.php
- Classes/Service/GeneratorService.php
- Classes/Service/HttpPush/AbstractHttpPush.php
- Classes/Service/HttpPush/SvgHttpPush.php
- Classes/Service/InlineAssetsService.php
- Classes/StaticFileCacheObject.php
- Classes/Traits/CacheTrait.php
- ext_localconf.php
- ext_tables.php
btw/ most of the "comments" are written twice within the same file ; intentional?
ref. https://github.com/lochmueller/staticfilecache/blob/master/Classes/StaticFileCacheObject.php
> [CLEANUP] comment/declare order & TYPO3_MODE checks

- Classes/Service/InlineAssets/InlineScripts.php
- Classes/Service/InlineAssets/InlineStyles.php
utf8 chars where disrupted while replacing `\v` | `\h`
> [OPT] utf8-save replace

- Classes/Service/CookieService.php
- ext_localconf.php
- ext_tables.php
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.0/Deprecation-92947-DeprecateTYPO3_MODEAndTYPO3_REQUESTTYPEConstants.html#typo3-mode-usage-as-global-script-file-security-gate
> [SWT] TYPO3_MODE

- .gitignore
- Classes/Configuration.php
- Classes/Generator/PhpGenerator.php
- Documentation/Configuration/Htaccess.rst
- Documentation/Configuration/Nginx.rst
- ext_conf_template.txt
If you're using nginx to host your TYPO3 website with ext:staticfilecache you cannot get headers send to the visitors browsers, because nginx does not support setting headers outside of the vhost configuration. This feature will deliver all static content via a php file, which will set the configured headers for your cached resources.
Related Issue
-------------
#343
> [FEATURE] Add php file generator for use with nginx

- Classes/Generator/PhpGenerator.php
Escape single quotes instead of double quotes
Fix a bug when using single quotes in headers like Content-Security-Policy headers. As the php template outputs headers via the `header('...')` method, the escaping of double quotes has been changed to escaping single quotes.
> [BUGFIX] Escape single quotes instead of double quotes

- Classes/Generator/ConfigGenerator.php
- Classes/Generator/HtaccessGenerator.php
- Classes/Middleware/FallbackMiddleware.php
- Classes/Service/ConfigurationService.php
- ext_conf_template.txt
This PR add the headers that are stored in xxx.config.json to the response correctly.
In fact, when using the FallbackMiddleware, the headers were not added correctly.
Related Issue
-------------
#382
> Fix #382 - Add headers that are stored in xxx.config.json correctly

- Classes/Command/AbstractCommand.php
- Classes/Middleware/FallbackMiddleware.php
This PR makes the extension work under typo3/cms-core:v12.2.0 as well as symfony/console:v6.2.5. This has been successfully tested in one sample project. This fixes two error messages:
- `implode(): Argument #2 ($array) must be of type ?array, string given in Classes/Middleware/FallbackMiddleware.php line 96`
- `Fatal error: Declaration of SFC\Staticfilecache\Command\AbstractCommand::setDescription($description) must be compatible with Symfony\Component\Console\Command\Command::setDescription(string $description): static in Classes/Command/AbstractCommand.php on line 21`
Related Issue
-------------
...
More Details
------------
- I only fixed one ocurrence of a broken implode use, there may be more errors to fix and this PR just makes it so the project …
> Restore typo3v12/symfony compability (vaguely tested in one instance)

- Classes/Configuration.php
- Classes/Controller/BackendController.php
- Classes/ViewHelpers/Format/StripEmptyVerticalSpacesViewHelper.php
- Resources/Private/Layouts/Backend.html
- Resources/Private/Partials/Backend/ListEntry.html
- Resources/Private/Templates/Backend/Boost.html
- Resources/Private/Templates/Backend/List.html
- Resources/Private/Templates/Backend/Support.html
- Resources/Private/Templates/Htaccess.html
- ext_conf_template.txt
Fully cacheable responses must avoid using Content-Security-Policy nonce values in HTTP headers and the generated HTML markup. This change adjusts the TYPO3 `PolicyBehavior` to aim for cacheable responses and therefore to use static hash values instead of dynamic nonce values.
* #389
* https://review.typo3.org/c/Packages/TYPO3.CMS/+/80554 (required TYPO3 v12 core change)
* the configuration properties `validHtaccessHeaders` and `validFallbackHeaders` were extended by `Content-Security-Policy` (this has to be adjusted manually in the file`system/settings.php` of the corresponding TYPO3 instance)
* the Apache `.htaccess` generator was adjusted to update the reporting URI that might potentially being used the `Content-Security-Policy` HTTP header, e.g. the corresponding section in the …
> 🛠️  [TASK] Handle Content-Security-Policy headers of TYPO3 v12

- Classes/Middleware/FrontendUserMiddleware.php
Hello, I am getting an error with sys_redirct URLs in `staticfilecache/Classes/Middleware/FrontendUserMiddleware.php`
`$feUser->appendCookieToResponse` tries to access `$GLOBALS['TYPO3_REQUEST']`, which is not set in this situation.
TYPO3 Exception Screenshot:
> https://github.com/lochmueller/staticfilecache/assets/84477901/ea573bde-e84e-4d5f-babd-9e2af569479a
Related Issue
-------------
none
More Details
------------
This PR sets the `$GLOBALS['TYPO3_REQUEST']` variable to the current `$request` available in the middleware.
Both are typed as `TYPO3\CMS\Core\Http\ServerRequest`.
Best regards.
> Redirect error when using felogin

- Classes/Cache/Rule/NoWorkspacePreview.php
In TYPO3 v13 `TypoScriptFrontendController->getContext()` has been marked as @internal`.
> [TASK] Use context API instead of TSFE

- Classes/Domain/Repository/CacheRepository.php
In Doctrine DBAL v4, as described in the [documentation](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Database/QueryBuilder/Index.html#database-query-builder-create-named-parameter), support for using the `\PDO::PARAM_*` constants has been dropped in favor of the enum types. This should be migrated to `Connection::PARAM_*` in order to be compatible with TYPO3 v13 later on. `Connection::PARAM_*` can already be used now as it is compatible with TYPO3 11 and 12.
> [TASK] Use Connection instead of PDO

- Classes/Service/ClientService.php
- ext_conf_template.txt
Related Issue
-------------
#415
> [FEATURE] Add option to override default user agent for boost mode crawler

- Classes/Cache/Rule/NoNoCache.php
- Classes/Middleware/FrontendCacheMiddleware.php
- Configuration/RequestMiddlewares.php
In TYPO3 v13, the [frontend.cache.instruction](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/RequestLifeCycle/RequestAttributes/FrontendCacheInstruction.html#frontend-cache-instruction) got introduced as a replacement for the now internal TypoScriptFrontendController->no_cache property.
During development / implementation for an TYPO3 v13.2.1 installation i saw, that the middleware hasn't been implemented yet, which results in an error in the backend after installation.
Possibly #410
> [BUGFIX] Added missing middleware implementing frontend.cache.instruction for TYPO3 v13

- Classes/Controller/BackendController.php
The Support-Tab in the Backend-Module shows the Boost-Template (too) and not the support-template. Changed this to show the Support-Template.
More Details
------------
Just noticed while clicking through the Backend-Module that the Support-Tab show the same content as the Boost-Tab (but with error message). Fixed that here :)
> FIX: The BackendController::supportAction show the Boost-Template instead of the Support-Template

- Classes/Cache/Listener/T3CrawlerIndexingProcessListener.php
- Configuration/Services.yaml
- Documentation/Configuration/Htaccess.rst
- Documentation/Configuration/Nginx.rst
Fix #428 - Add EXT:crawler indexing check for htaccess, nginx and fallback middleware
> Disable cache for EXT:crawler indexing requests

- Classes/Generator/HtaccessGenerator.php
- ext_conf_template.txt
This patch helps to handle the max header size problem. You can define your own header size if your webserver respect another size. You can also define a custom header size buffer for you to prevent that you always use the max size.
> [FEATURE] Optimize max header size handling

- Classes/Cache/StaticFileBackend.php
- Classes/Command/BoostQueueCommand.php
- Classes/Command/FlushCacheCommand.php
- Classes/Domain/Repository/CacheRepository.php
- Classes/Domain/Repository/QueueRepository.php
- Classes/Service/ClientService.php
- Classes/Service/QueueService.php
- ext_tables.sql
Improves the performance of boost mode cache flush and crawling to refill the cache.
Cache flush (80.000 entries in cache), before:
```sh
time ./vendor/bin/typo3 staticfilecache:flushCache
real    2m51.869s
user    0m19.032s
sys     0m15.217s
```
and after:
```sh
time ./vendor/bin/typo3 staticfilecache:flushCache
real    0m35.927s
user    0m6.952s
sys     0m6.502s
```
It's 5x (!) faster than before.
Crawling to refill the cache is also improved, but the numbers are not that massive.
Related Issue
-------------
Fixes #435 
More Details
------------
Please review and test to give me feedback. I am willing to adapt things.
> Performance improvements for boost mode

- Classes/Middleware/PrepareMiddleware.php
Makes preloading of font assets working.
Related Issue
-------------
Fixes #443.
More Details
------------
I tried to keep the change in code as minimum as possible.
> [BUGFIX] Include crossorigin attribute in link header when preloading font assets
