Classes/Cache/StaticFileBackend.php

[BUGFIX] Add missing method to flush by tags

---

Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf

Hello there,
I have updated the German translation and added the missing phrases.

[FEATURE] update German translation

---

ext_conf_template.txt
ext_localconf.php

Please merge if you find this useful.

Option to disable static file cache in development

---

Classes/StaticFileCache.php

IDNA Encode URLs before using them as cache key

---

Classes/Service/QueueService.php

Increase guzzle cookie session time

---

Classes/Hook/LogoffFrontendUser.php
Classes/Service/CookieService.php
Documentation/Configuration/Htaccess.rst

BUGFIX für BE user logout

---

Classes/Cache/StaticFileBackend.php
Classes/StaticFileCache.php

cache-backend either returns an cache entry or false otherwise.

[FIX] count usage on non-array

---

Resources/Private/Language/da.locallang.xlf
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Templates/Module.html

Added language Danish
Minor corrections in German and English lang-files
Added label to template

[TASK] Add lang DA + minor improvements

---

Documentation/Configuration/Htaccess.rst

...
Related Issue
-------------
...
More Details
------------
- Work in Progess?
- Open Issues?

[FIX] line indents on Htaccess.rst

---

Documentation/Configuration/Nginx.rst

Resolves: #142
Update Nginx configuration example using ports in SFC 8.0
Related Issue
-------------
#142
More Details
------------
See https://nginx.org/en/docs/http/ngx_http_core_module.html
`$server_port`
port of the server which accepted a request

[DOC] Update Nginx configuration example using ports in SFC 8.0

---

Documentation/Configuration/Htaccess.rst

The new version should make the example htaccess work with things like
Loadbalancers (tested with AWS Application Load Balancer)

Update example .htaccess

---

Documentation/StaticDynamic/Index.rst

Also, change the CLI username.

Change to correct executable and parameter

---

Resources/Private/Templates/Backend/Support.html

...
Related Issue
-------------
...
More Details
------------
- Work in Progess?
- Open Issues?

[TASK] improve support text and spelling

---

Documentation/KnownProblems/Index.rst
Documentation/NeedSpeed/Index.rst
PULL_REQUEST_TEMPLATE.md
README.md
ext_conf_template.txt

- Fix some typos
- Streamline usage of ".htaccess" in ext_conf_template.php

[TASK] Fix typos

---

Classes/Cache/StaticFileBackend.php

This change allows you to delete the entire StaticFileCache from the file system. Then it will be recreated.

[TASK] allow deleting the cache from the file system.

---

Documentation/Configuration/Htaccess.rst

Set right MimeType to .gzip files and handle them as compressed files
...
Related Issue
-------------
https://github.com/lochmueller/staticfilecache/issues/225 https://github.com/lochmueller/staticfilecache/issues/227
...

GZIP correction (if compression is activated)

---

Classes/Generator/HtaccessGenerator.php

[HOTFIX] strip double-quote from existing link header

---

Classes/Middleware/PrepareMiddleware.php

Fix typo in $configuration

---

Classes/Middleware/PrepareMiddleware.php

Check if $cacheTags is not empty before adding header

---

Classes/Cache/StaticFileBackend.php
Classes/Service/ConfigurationService.php
Classes/Service/EnvironmentService.php
Classes/Service/HtaccessConfigurationService.php
Classes/Service/HttpPush/AbstractHttpPush.php
Classes/Service/HttpPushService.php
Classes/Service/RemoveService.php
Classes/Service/TypoScriptFrontendService.php
Configuration/TCA/Overrides/pages.php

https://wiki.php.net/rfc/calls_in_constant_expressions

adapt constant expressions

---

Classes/Cache/Rule/ValidDoktype.php

fixes #327
...
Related Issue
-------------
...
More Details
------------
- Work in Progress?
- Open Issues?

Fix missing namespace import

---

ext_conf_template.txt

?may need to add `woff2` @ line 21 ?
https://github.com/lochmueller/staticfilecache/blob/d41f455088658afc23f98109b536208878341428/Classes/Service/HttpPush/FontHttpPush.php#L19-L29

update possible `sendHttp2PushFileExtensions`

---

Classes/Service/HttpPush/StyleHttpPush.php

https://github.com/TYPO3/typo3/blob/8c1cf639a18edaf9a98d5943f56da66b7d2510a0/typo3/sysext/core/Classes/Page/PageRenderer.php#L2207-L2208

[OPT] StyleHttpPush w/o media=print

---

Classes/Service/HttpPush/FontHttpPush.php

ref. https://github.com/lochmueller/staticfilecache/pull/337#issuecomment-1108939740

update FontHttpPush ; incl. `woff2`

---

Classes/Service/InlineAssets/InlineScripts.php

sorry ; this function is kinda triky // greetings

[OPT] remove spaces @ JS

---

Documentation/Installation/Index.rst

...
Related Issue
-------------
...
More Details
------------
- Work in Progress?
- Open Issues?

[DOCS] Fix typo in installation documentation

---

Documentation/Faq/Index.rst

I have revised the FAQ page:
- optimized layout
- spellchecking
- removed writeup on caching section because of outdated link

[DOCS] Revise FAQ page

---

Documentation/ChangeLog/Index.rst

That's the last change to the docs for the moment. Feel free to create a new release.
Thx a lot for your patience.

[DOCS] Improve changelog page

---

Documentation/Configuration/Nginx.rst

Updated nginx configuration directives for use of the php generator.

[TASK] Update nginx configuration directives when using php generator

---

Classes/Generator/PhpGenerator.php
Resources/Private/Templates/Php.html
ext_conf_template.txt

Use a template file to render the php file when using the php generator.

[TASK] Use template for php generator

---

Classes/Controller/BackendController.php
Classes/Hook/LogoffFrontendUser.php
Classes/Middleware/FallbackMiddleware.php
Configuration/Backend/Modules.php
Configuration/Icons.php
Resources/Private/Layouts/Backend.html
composer.json

...
Related Issue
-------------
...
More Details
------------
- Work in Progress? yes
- Open Issues? backend Module Frame is rendered twice:

[BUGFIX] fix TYPO3 12 Backend

---

Classes/Hook/DatamapHook.php
Classes/Service/CookieService.php

...
Related Issue
-------------
...
More Details
------------
- Work in Progress?
- Open Issues?

🐛 fix cookie handling

---

Classes/Command/BoostQueueCommand.php
Classes/Command/FlushCacheCommand.php

Stay in line with the `Symfony\Component\Console\Command:execute` function signatur to prevent exception

---

Classes/Controller/BackendController.php

Fixes the call to `\count` that expects a `Countable|array` argument and not a Generator.
Optimizes the memory hungry `iterator_to_array` calls.

[BUGFIX] Fix boostAction to properly handle Generator iterables

---

Documentation/Configuration/Htaccess.rst

[CLS] DOC:htacces TABs

---

ext_conf_template.txt

@lochmueller I came across this [link](https://github.com/lochmueller/staticfilecache/issues/389) and then to this setting and was surprised that Oli Hader is saved here :)

Small typo in ext_conf_template.txt

---

Classes/Cache/RemoteFileBackend.php

The FreezableBackendInterface originated from the original FileBackend but is not used within this extension. Since the interface was removed from the TYPO3 core in version 14, it can be safely dropped here as well.
More Details
------------
https://review.typo3.org/c/Packages/TYPO3.CMS/+/90434

fix: remove FreezableBackendInterface
